push.manifest:
    path: /push/manifest.json
    defaults: { _controller: push.controller:manifest }

push.service_worker:
    # /firebase-messaging-sw.js is the required filename and path
    # for FCM to work
    path: /firebase-messaging-sw.js
    defaults: { _controller: push.controller:service_worker }

push.register_user:
    path: /push/register_user
    defaults: { _controller: push.controller:register_user }
    
push.unsubscribe_user:
    path: /push/unregister_user
    defaults: { _controller: push.controller:unregister_user }
    
push.is_registered_user:
    path: /push/is_registered_user
    defaults: { _controller: push.controller:is_registered_user }
    
push.is_user_loggedin:  
    path: /push/is_user_loggedin
    defaults: { _controller: push.controller:is_user_loggedin }