services:
    push.controller:
        class: imkingdavid\push\controller\push
        arguments:
            - '@template.twig.environment'
            - '@request'
            - '@config'
            - '@dbal.conn'
            - '%core.table_prefix%'
            - '%core.root_path%'

    push.listener:
        class: imkingdavid\push\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@controller.helper'
        tags:
            - { name: event.listener }