services:
    push.controller:
        class: imkingdavid\push\controller\push
        arguments:
            - '@template.twig.environment'
            - '@request'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@controller.helper'
            - '%core.table_prefix%'
            - '%core.root_path%'

    push.listener:
        class: imkingdavid\push\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@controller.helper'
        tags:
            - { name: event.listener }
            
    push.notification.method.browser:
        class: imkingdavid\push\notifications\method\browser
        shared: false
        arguments:
            - '@user_loader'
            - '@user'
            - '@config'
            - '@dbal.conn'
            - '@log'
            - '@filesystem'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%push_user_tokens'
        tags:
            - { name: notification.method }